### ISSUE TITLE
Checklist for 1.0.0

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#250]
Lots of stuff to remember, so here's a checklist in (almost) no particular order and subject to change:
- [x] [GH-261] ~~Move base boxes creation scripts out to a separate repository~~
- [x] Implement `vagrant lxc sudoers-install`
- [x] Publish new provisionerless base boxes to vagrant cloud and update links / docs
- [x] [Review base boxes issues](https://github.com/fgrehm/vagrant-lxc-base-boxes/issues?state=open)
- [x] Make sure `vagrant up` in parallel does not break with new boxes
- [x] Do another round of vagrant / lxc versions compatibility check
- [x] Release
